select ?X, ?Y, ?Z where ?X httpwwww3org19990222-rdf-syntax-nstype httpwwwlehigheduzhp220040401univ-benchowlGraduateStudent . ?Y httpwwww3org19990222-rdf-syntax-nstype httpwwwlehigheduzhp220040401univ-benchowlUniversity . ?Z httpwwww3org19990222-rdf-syntax-nstype httpwwwlehigheduzhp220040401univ-benchowlDepartment . ?X httpwwwlehigheduzhp220040401univ-benchowlmemberOf ?Z . ?Z httpwwwlehigheduzhp220040401univ-benchowlsubOrganizationOf ?Y . ?X httpwwwlehigheduzhp220040401univ-benchowlundergraduateDegreeFrom ?Y .