select ?v0, ?v1, ?v3, ?v4, ?v5, ?v6, ?v7, ?v8, ?v9 where ?v0 httppurlorggoodrelationsincludes ?v1 . httpdbuwaterloocagalucwsdbmRetailer633 httppurlorggoodrelationsoffers ?v0 . ?v0 httppurlorggoodrelationsprice ?v3 . ?v0 httppurlorggoodrelationsserialNumber ?v4 . ?v0 httppurlorggoodrelationsvalidFrom ?v5 . ?v0 httppurlorggoodrelationsvalidThrough ?v6 . ?v0 httpschemaorgeligibleQuantity ?v7 . ?v0 httpschemaorgeligibleRegion ?v8 . ?v0 httpschemaorgpriceValidUntil ?v9 .